import Navbar from '../components/Navbar';
import * as React from 'react';
import Head from 'next/head';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faEnvelope, faPhone } from '@fortawesome/free-solid-svg-icons';
const About = () => {
  return (
    <>
      <Head>
        <title>Contact | Splendora Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='flex flex-col flex-1 h-full items-center bg-whitePrimary dark:bg-blackSecondary dark:text-white font-[BaiJamjuree]'>
        <Navbar></Navbar>
        <div className='flex gap-10 max-w-[1024px] justify-between items-center my-24'>
          <div className='flex-1'>
            <p className='text-6xl font-bold text-transparent leading-[48px] bg-clip-text bg-gradient-to-r from-green-300 via-blue-500 to-purple-600'>
              Get in touch
            </p>
            <p>
              Interested in working with me? Looking for a young and passionate
              developer? Reach out to me through this form and I&apos;ll get
              back to you in the next 48hours. Or contact me directly at office
              hours.
            </p>
            <span>
              <FontAwesomeIcon icon={faEnvelope} className='gradient-text' />
              <span>minhthuong906@gmail.com</span>
            </span>
            <span>
              <FontAwesomeIcon icon={faPhone} className='fill-transparent bg-clip-text bg-gradient-to-r from-green-300 via-blue-500 to-purple-600' />
              <span>(+84) 938-619-729</span>
            </span>
          </div>
          <form className='flex flex-col flex-1'>
            <label>Your name</label>
            <input
              type={'text'}
              name='name'
              placeholder='Enter your name'
            ></input>
            <label>Your Email</label>
            <input
              type={'text'}
              name='name'
              placeholder='Enter your email'
            ></input>
            <label>Tell me a bit about what you are looking for?</label>
            <input
              type={'text'}
              name='name'
              placeholder='Enter your message'
            ></input>
            <button>Submit now</button>
          </form>
        </div>
      </main>
    </>
  );
};

export default About;
