import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import Navbar from './components/Navbar/index';
import Footer from './components/Footer/index';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faSplotch } from '@fortawesome/free-solid-svg-icons';
import Tilt from './components/Tilt';
import { useRouter } from 'next/router';
const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const router = useRouter();
  const handleMoreAboutButton = () => {
    router.push('/about');
  };
  const handleContactMeButton = () => {
    router.push('/contact');
  };
  return (
    <>
      <Head>
        <title>Home | Splendora Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main
        className={
          'flex flex-col flex-1 h-full items-center bg-whitePrimary dark:bg-blackSecondary dark:text-white font-[BaiJamjuree]'
        }
      >
        <Navbar></Navbar>
        <div className='flex flex-row max-md:flex-col-reverse flex-1 max-w-[1024px] justify-between items-center my-24'>
          <div>
            <div className='text-5xl font-extrabold leading-[64px]'>
              <p className='gradient-text'>Hello, I&apos;m Minh Thuong,</p>
              junior web developer based in HoChiMinh City, VietNam.
            </div>
            <p className='text-xl pt-4 leading-7'>
              An aspiring junior web developer in VietNam. I specilize in
              developing responsive websites for mobile and desktop.
            </p>
            <div className='pt-4'>
              <button
                className='rounded-3xl font-semibold px-6 py-3 bg-gradient-to-r from-green-300 via-blue-500 to-purple-600 hover:shadow-[0_5px_30px_0px_rgba(0,0,0,0.5)] dark:hover:shadow-[0_5px_30px_0px_rgba(255,255,255,0.5)] transition duration-300'
                onClick={handleMoreAboutButton}
                type='button'
              >
                MORE ABOUT ME
              </button>
              <button
                className='rounded-3xl font-semibold bg-red-500 px-6 py-3 ml-4 border border-black dark:border-whitePrimary bg-transparent hover:bg-purple-600 hover:border-purple-600 dark:hover:bg-green-300 dark:hover:border-green-300 hover:shadow-[0_5px_30px_0px_rgba(0,0,0,0.5)] dark:hover:shadow-[0_5px_30px_0px_rgba(255,255,255,0.5)] transition duration-300'
                type='button'
                onClick={handleContactMeButton}
              >
                CONTACT ME
              </button>
            </div>
          </div>
          <Tilt className='flex items-center justify-center rounded-md w-[300px] h-min shadow-[0_5px_30px_0px_rgba(0,0,0,0.5)] dark:shadow-[0_5px_30px_0px_rgba(255,255,255,0.5)]'>
            <Image
              className='rounded-md '
              src='/my-photo.jpg'
              alt='13'
              width={200}
              height={100}
              priority
            />
          </Tilt>
        </div>
        <div className='w-full relative h-24 bg-gradient-to-r from-green-300 via-blue-500 to-purple-600 '>
          <div className='w-[110%] absolute -left-10 flex h-24 bg-blackSecondary dark:bg-white text-black -rotate-2'>
            <div className='h-24 animate-slideLoop font-bold flex gap-6 text-4xl items-center gradient-text'>
              <FontAwesomeIcon icon={faSplotch} className='text-blue-500' />
              Design
              <FontAwesomeIcon icon={faSplotch} className='text-blue-500' />
              Develop
              <FontAwesomeIcon icon={faSplotch} className='text-blue-500' />
              Discover
              <FontAwesomeIcon icon={faSplotch} className='text-blue-500' />
              Design
              <FontAwesomeIcon icon={faSplotch} className='text-blue-500' />
              Develop
              <FontAwesomeIcon icon={faSplotch} className='text-blue-500' />
              Discover
              <FontAwesomeIcon icon={faSplotch} className='text-blue-500' />
              Design
              <FontAwesomeIcon icon={faSplotch} className='text-blue-500' />
              Develop
              <FontAwesomeIcon icon={faSplotch} className='text-blue-500' />
              Discover
              <FontAwesomeIcon icon={faSplotch} className='text-blue-500' />
              Design
              <FontAwesomeIcon icon={faSplotch} className='text-blue-500' />
              Design
              <FontAwesomeIcon icon={faSplotch} className='text-blue-500' />
              Develop
              <FontAwesomeIcon icon={faSplotch} className='text-blue-500' />
              Discover
              <FontAwesomeIcon icon={faSplotch} className='text-blue-500' />
              Design
              <FontAwesomeIcon icon={faSplotch} className='text-blue-500' />
              Develop
              <FontAwesomeIcon icon={faSplotch} className='text-blue-500' />
              Discover
              <FontAwesomeIcon icon={faSplotch} className='text-blue-500' />
              Design
              <FontAwesomeIcon icon={faSplotch} className='text-blue-500' />
              Develop
              <FontAwesomeIcon icon={faSplotch} className='text-blue-500' />
              Discover
              <FontAwesomeIcon icon={faSplotch} className='text-blue-500' />
              Design
            </div>
            <div className='h-24 animate-slideLoop2 font-bold flex gap-6 text-4xl items-center text-transparent bg-clip-text bg-gradient-to-r from-green-300 via-blue-500 to-purple-600'>
              <FontAwesomeIcon icon={faSplotch} className='text-blue-500' />
              Design
              <FontAwesomeIcon icon={faSplotch} className='text-blue-500' />
              Develop
              <FontAwesomeIcon icon={faSplotch} className='text-blue-500' />
              Discover
              <FontAwesomeIcon icon={faSplotch} className='text-blue-500' />
              Design
              <FontAwesomeIcon icon={faSplotch} className='text-blue-500' />
              Develop
              <FontAwesomeIcon icon={faSplotch} className='text-blue-500' />
              Discover
              <FontAwesomeIcon icon={faSplotch} className='text-blue-500' />
              Design
              <FontAwesomeIcon icon={faSplotch} className='text-blue-500' />
              Develop
              <FontAwesomeIcon icon={faSplotch} className='text-blue-500' />
              Discover
              <FontAwesomeIcon icon={faSplotch} className='text-blue-500' />
              Design
              <FontAwesomeIcon icon={faSplotch} className='text-blue-500' />
              Design
              <FontAwesomeIcon icon={faSplotch} className='text-blue-500' />
              Develop
              <FontAwesomeIcon icon={faSplotch} className='text-blue-500' />
              Discover
              <FontAwesomeIcon icon={faSplotch} className='text-blue-500' />
              Design
              <FontAwesomeIcon icon={faSplotch} className='text-blue-500' />
              Develop
              <FontAwesomeIcon icon={faSplotch} className='text-blue-500' />
              Discover
              <FontAwesomeIcon icon={faSplotch} className='text-blue-500' />
              Design
              <FontAwesomeIcon icon={faSplotch} className='text-blue-500' />
              Develop
              <FontAwesomeIcon icon={faSplotch} className='text-blue-500' />
              Discover
              <FontAwesomeIcon icon={faSplotch} className='text-blue-500' />
              Design
            </div>
          </div>
        </div>

        <div className='w-full max-w-[1024px] my-24'>
          <h2 className='font-bold text-3xl'>My Tech Stack</h2>
          <div className='flex flex-row justify-between max-lg:grid grid-cols-3 gap-y-4 max-md:grid-cols-2 my-10 lg:px-10'>
            <div className='flex flex-col align-middle text-center items-center font-bold text-xl text-blue-500'>
              <Image
                className='rounded-md'
                src='/html-logo.png'
                alt='html'
                width={80}
                height={80}
                priority
              />
              HTML
            </div>
            <div className='flex flex-col align-middle text-center items-center font-bold text-xl text-blue-500'>
              <Image
                className='rounded-md'
                src='/css-logo.png'
                alt='css'
                width={70}
                height={80}
                priority
              />
              CSS
            </div>
            <div className='flex flex-col align-middle text-center items-center font-bold text-xl text-blue-500'>
              <Image
                className='rounded-md flex-1'
                src='/reactjs-logo.png'
                alt='react'
                width={80}
                height={80}
                priority
              />
              REACTJS
            </div>
            <div className='flex flex-col align-middle text-center items-center font-bold text-xl text-blue-500'>
              <Image
                className='rounded-md'
                src='/node-logo.png'
                alt='node'
                width={80}
                height={80}
                priority
              />
              NODE
            </div>
            <div className='flex flex-col align-middle text-center items-center font-bold text-xl text-blue-500'>
              <Image
                className='rounded-md'
                src='/database-logo.png'
                alt='react'
                width={80}
                height={80}
                priority
              />
              NoSQL/SQL Database
            </div>
          </div>
        </div>

        <div className='max-w-[1024px] mb-10'>
          <h2 className='font-bold text-3xl'>Projects I&apos;ve worked on</h2>
          <div className='flex bg-slate-600 mt-10 rounded-lg'>
            <div className='flex-1 px-4 py-4'>
              <div className='bg-red-900 w-full h-full rounded-lg min-h-[180px] max-h-[250px]'>
                <Image
                  className='!relative object-cover h-[unset]'
                  src='/yt_1200.png'
                  alt='ytClone'
                  fill
                />
              </div>
            </div>
            <div className='flex-1 flex flex-col px-4 py-4'>
              <div className='flex'>
                <button className='rounded-xl bg-white px-3 py-1 text-black mr-2 font-semibold'>
                  ReactJS
                </button>
                <button className='rounded-xl bg-white px-3 py-1 text-black mr-2 font-semibold'>
                  Node
                </button>
                <button className='rounded-xl bg-white px-3 py-1 text-black mr-2 font-semibold'>
                  API
                </button>
              </div>
              <div className='text-lg font-bold mt-2'>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua.
              </div>
              <p className='text-gray-500 mt-1'>lorem ipsum</p>
            </div>
          </div>
          <div className='flex bg-slate-600 mt-4 rounded-lg'>
            <div className='flex-1 px-4 py-4'>
              <div className='bg-red-900 w-full h-full rounded-lg min-h-[180px] max-h-[250px]'>
                <Image
                  className='!relative object-cover h-[unset]'
                  src='/home-fixing.jpg'
                  alt='home-fixing'
                  fill
                />
              </div>
            </div>
            <div className='flex-1 flex flex-col px-4 py-4'>
              <div className='flex'>
                <button className='rounded-xl bg-white px-3 py-1 text-black mr-2 font-semibold'>
                  ReactJS
                </button>
                <button className='rounded-xl bg-white px-3 py-1 text-black mr-2 font-semibold'>
                  Service
                </button>
              </div>
              <div className='text-lg font-bold mt-2'>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua.
              </div>
              <p className='text-gray-500 mt-1'>lorem ipsum</p>
            </div>
          </div>
          <div className='flex bg-slate-600 mt-4 rounded-lg'>
            <div className='flex-1 px-4 py-4'>
              <div className='bg-red-900 w-full h-full rounded-lg min-h-[180px]'></div>
            </div>
            <div className='flex-1 flex flex-col px-4 py-4'>
              <div className='flex'>
                <button className='rounded-xl bg-white px-3 py-1 text-black mr-2 font-semibold'>
                  ReactJS
                </button>
                <button className='rounded-xl bg-white px-3 py-1 text-black mr-2 font-semibold'>
                  Web SDK
                </button>
              </div>
              <div className='text-lg font-bold mt-2'>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua.
              </div>
              <p className='text-gray-500 mt-1'>lorem ipsum</p>
            </div>
          </div>
        </div>
        <Footer></Footer>
      </main>
    </>
  );
}
