import Navbar from '../components/Navbar';
import * as React from 'react';
import Head from 'next/head';
import Footer from '../components/Footer';
const Projects = () => {
  return (
    <>
      <Head>
        <title>My Projects | Splendora Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main
        className={
          'flex flex-col flex-1 h-full items-center bg-whitePrimary dark:bg-blackSecondary dark:text-white font-[BaiJamjuree]'
        }
      >
        <Navbar></Navbar>

        <Footer></Footer>
      </main>
    </>
  );
};

export default Projects;
